<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>ISM+</AssemblyName>
    <Company>Open Source Developer, Satyam Jha</Company>
    <Authors>Open Source Developer, Satyam Jha</Authors>
    <Product>ISM+</Product>
    <AssemblyTitle>ISM+</AssemblyTitle>
    <Title>ISM+</Title>
    <Version>1.0.3</Version>
    <FileVersion>1.0.3.0</FileVersion>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <ApplicationIcon>Icon1.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
    <Resource Include="Icon1.ico" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
  </ItemGroup>

</Project>
